spring.application.name=society-mangement
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/society_db
spring.datasource.username=D3_93092_Sukirti
spring.datasource.password=manager

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
jwt.secret=my-super-secret-key-for-jwt-signing-which-is-at-least-32-bytes-long

logging.level.org.springframework.security=DEBUG
